import { CharacterDefinition, CharacterId } from './types';
export const CHARACTERS: CharacterDefinition[] = [
{id:'juwon',nameKo:'주원쌤',nameEn:'Juwon',role:'Balanced Leader',maxHp:195,speed:111,attackPower:8,attackRange:40,preferredCombatDistance:35,attackCooldown:0.92,skillPower:16,skillNameKorean:'종례 선언',skillNameEnglish:'Final Bell Command',skillCooldown:15,skillDescription:'감속 장판 + 보호',gameplayEffect:'enemies slow, self shield',bodyRadius:20,fallbackColor:'#5f7bd8',spritePath:'/assets/characters/juwon/sprite.png',portraitPath:'/assets/characters/juwon/portrait.png',motif:'🔔'},
{id:'kyungmin',nameKo:'고경민',nameEn:'Kyungmin',role:'Burst',maxHp:162,speed:123,attackPower:9,attackRange:41,preferredCombatDistance:35,attackCooldown:0.96,skillPower:24,skillNameKorean:'돌고래 고음',skillNameEnglish:'Dolphin High Note',skillCooldown:16,skillDescription:'원형 폭발 넉백',gameplayEffect:'blast knockback stun',bodyRadius:18,fallbackColor:'#ffd33f',spritePath:'/assets/characters/kyungmin/sprite.png',portraitPath:'/assets/characters/kyungmin/portrait.png',motif:'🎤'},
{id:'hyunjun',nameKo:'홍현준',nameEn:'Hyunjun',role:'Speed',maxHp:150,speed:145,attackPower:7,attackRange:38,preferredCombatDistance:33,attackCooldown:0.82,skillPower:13,skillNameKorean:'철학적 질문',skillNameEnglish:'Philosophical Question',skillCooldown:14,skillDescription:'혼란 + 이속증가',gameplayEffect:'confuse nearby and haste',bodyRadius:17,fallbackColor:'#2f3d5c',spritePath:'/assets/characters/hyunjun/sprite.png',portraitPath:'/assets/characters/hyunjun/portrait.png',motif:'❓'},
{id:'chanyoung',nameKo:'박찬영',nameEn:'Chanyoung',role:'Recovery',maxHp:186,speed:114,attackPower:8,attackRange:40,preferredCombatDistance:35,attackCooldown:0.9,skillPower:22,skillNameKorean:'긍정 에너지',skillNameEnglish:'Positive Energy',skillCooldown:15,skillDescription:'회복 + 방어',gameplayEffect:'heal and defense',bodyRadius:20,fallbackColor:'#f0a03a',spritePath:'/assets/characters/chanyoung/sprite.png',portraitPath:'/assets/characters/chanyoung/portrait.png',motif:'✨'},
{id:'hyowon',nameKo:'임효원',nameEn:'Hyowon',role:'Trickster',maxHp:158,speed:130,attackPower:7,attackRange:40,preferredCombatDistance:34,attackCooldown:0.86,skillPower:15,skillNameKorean:'수상한 장난',skillNameEnglish:'Sneaky Prank',skillCooldown:12,skillDescription:'함정 설치',gameplayEffect:'trap stun',bodyRadius:17,fallbackColor:'#ff8a3d',spritePath:'/assets/characters/hyowon/sprite.png',portraitPath:'/assets/characters/hyowon/portrait.png',motif:'🪤'},
{id:'dongha',nameKo:'최동하',nameEn:'Dongha',role:'Utility',maxHp:172,speed:120,attackPower:8,attackRange:42,preferredCombatDistance:36,attackCooldown:0.9,skillPower:14,skillNameKorean:'아이디어 폭주',skillNameEnglish:'Idea Overdrive',skillCooldown:12,skillDescription:'랜덤 장치',gameplayEffect:'spawn random device',bodyRadius:19,fallbackColor:'#91a3ad',spritePath:'/assets/characters/dongha/sprite.png',portraitPath:'/assets/characters/dongha/portrait.png',motif:'⚙️'},
{id:'heesun',nameKo:'장희선',nameEn:'Heesun',role:'Ranged Precision',maxHp:154,speed:122,attackPower:7,attackRange:86,preferredCombatDistance:72,attackCooldown:1.02,skillPower:22,skillNameKorean:'예쁜 필기구 투척',skillNameEnglish:'Pretty Stationery Throw',skillCooldown:10,skillDescription:'원거리 투사체',gameplayEffect:'long projectile',bodyRadius:16,fallbackColor:'#ff77b7',spritePath:'/assets/characters/heesun/sprite.png',portraitPath:'/assets/characters/heesun/portrait.png',motif:'✏️'},
{id:'soeun',nameKo:'박소은',nameEn:'Soeun',role:'Chaos',maxHp:160,speed:131,attackPower:6,attackRange:78,preferredCombatDistance:66,attackCooldown:0.88,skillPower:12,skillNameKorean:'곤충 출몰',skillNameEnglish:'Bug Swarm',skillCooldown:11,skillDescription:'벌레 떼 소환',gameplayEffect:'homing DoT panic',bodyRadius:16,fallbackColor:'#f3d73a',spritePath:'/assets/characters/soeun/sprite.png',portraitPath:'/assets/characters/soeun/portrait.png',motif:'🐞'}
];
export const byId=(id:CharacterId)=>CHARACTERS.find(c=>c.id===id)!;
