import { CharacterDefinition, CharacterId } from './types';
export const CHARACTERS: CharacterDefinition[] = [
{id:'juwon',nameKo:'주원쌤',nameEn:'Juwon',role:'Controller',maxHp:145,speed:115,attackPower:11,attackRange:48,attackCooldown:0.7,skillNameKorean:'종례 선언',skillNameEnglish:'Final Bell Command',skillCooldown:12,skillDescription:'감속 장판 + 보호',gameplayEffect:'enemies slow, self shield',fallbackColor:'#5f7bd8',spritePath:'/assets/characters/juwon/sprite.png',portraitPath:'/assets/characters/juwon/portrait.png',motif:'🔔'},
{id:'kyungmin',nameKo:'고경민',nameEn:'Kyungmin',role:'Burst',maxHp:120,speed:128,attackPower:14,attackRange:52,attackCooldown:0.65,skillNameKorean:'돌고래 고음',skillNameEnglish:'Dolphin High Note',skillCooldown:10,skillDescription:'원형 폭발 넉백',gameplayEffect:'blast knockback stun',fallbackColor:'#ffd33f',spritePath:'/assets/characters/kyungmin/sprite.png',portraitPath:'/assets/characters/kyungmin/portrait.png',motif:'🎤'},
{id:'hyunjun',nameKo:'홍현준',nameEn:'Hyunjun',role:'Speed',maxHp:100,speed:155,attackPower:10,attackRange:44,attackCooldown:0.55,skillNameKorean:'철학적 질문',skillNameEnglish:'Philosophical Question',skillCooldown:11,skillDescription:'혼란 + 이속증가',gameplayEffect:'confuse nearby and haste',fallbackColor:'#2f3d5c',spritePath:'/assets/characters/hyunjun/sprite.png',portraitPath:'/assets/characters/hyunjun/portrait.png',motif:'❓'},
{id:'chanyoung',nameKo:'박찬영',nameEn:'Chanyoung',role:'Recovery',maxHp:135,speed:122,attackPower:13,attackRange:50,attackCooldown:0.66,skillNameKorean:'긍정 에너지',skillNameEnglish:'Positive Energy',skillCooldown:12,skillDescription:'회복 + 방어',gameplayEffect:'heal and defense',fallbackColor:'#f0a03a',spritePath:'/assets/characters/chanyoung/sprite.png',portraitPath:'/assets/characters/chanyoung/portrait.png',motif:'✨'},
{id:'hyowon',nameKo:'임효원',nameEn:'Hyowon',role:'Trap',maxHp:118,speed:136,attackPower:11,attackRange:46,attackCooldown:0.63,skillNameKorean:'수상한 장난',skillNameEnglish:'Sneaky Prank',skillCooldown:9,skillDescription:'함정 설치',gameplayEffect:'trap stun',fallbackColor:'#ff8a3d',spritePath:'/assets/characters/hyowon/sprite.png',portraitPath:'/assets/characters/hyowon/portrait.png',motif:'🪤'},
{id:'dongha',nameKo:'최동하',nameEn:'Dongha',role:'Chaos Utility',maxHp:125,speed:124,attackPower:12,attackRange:48,attackCooldown:0.62,skillNameKorean:'아이디어 폭주',skillNameEnglish:'Idea Overdrive',skillCooldown:9,skillDescription:'랜덤 장치',gameplayEffect:'spawn random device',fallbackColor:'#91a3ad',spritePath:'/assets/characters/dongha/sprite.png',portraitPath:'/assets/characters/dongha/portrait.png',motif:'⚙️'},
{id:'heesun',nameKo:'장희선',nameEn:'Heesun',role:'Ranged Precision',maxHp:116,speed:126,attackPower:15,attackRange:55,attackCooldown:0.72,skillNameKorean:'예쁜 필기구 투척',skillNameEnglish:'Pretty Stationery Throw',skillCooldown:7,skillDescription:'원거리 투사체',gameplayEffect:'long projectile',fallbackColor:'#ff77b7',spritePath:'/assets/characters/heesun/sprite.png',portraitPath:'/assets/characters/heesun/portrait.png',motif:'✏️'},
{id:'soeun',nameKo:'박소은',nameEn:'Soeun',role:'Summoner Chaos',maxHp:122,speed:123,attackPower:9,attackRange:45,attackCooldown:0.58,skillNameKorean:'곤충 출몰',skillNameEnglish:'Bug Swarm',skillCooldown:8,skillDescription:'벌레 떼 소환',gameplayEffect:'homing DoT panic',fallbackColor:'#f3d73a',spritePath:'/assets/characters/soeun/sprite.png',portraitPath:'/assets/characters/soeun/portrait.png',motif:'🐞'}
];
export const byId=(id:CharacterId)=>CHARACTERS.find(c=>c.id===id)!;
