import { CharacterDefinition, CharacterId } from './types';
export const CHARACTERS: CharacterDefinition[] = [
{id:'juwon',nameKo:'주원쌤',nameEn:'Juwon',role:'Melee Bruiser',maxHp:195,baseMoveSpeed:122,attackType:'melee',attackPower:8,attackRange:42,preferredCombatDistance:36,attackCooldown:0.84,skillPower:16,skillNameKorean:'종례 선언',skillNameEnglish:'Final Bell Command',skillCooldown:15,skillDescription:'킥 충격파 + 보호',gameplayEffect:'kick burst + shield',bodyRadius:20,fallbackColor:'#5f7bd8',spritePath:'/assets/characters/juwon/sprite.png',portraitPath:'/assets/characters/juwon/portrait.png',motif:'🔔'},
{id:'kyungmin',nameKo:'고경민',nameEn:'Kyungmin',role:'Melee Burst',maxHp:170,baseMoveSpeed:122,attackType:'melee',attackPower:9,attackRange:40,preferredCombatDistance:34,attackCooldown:0.9,skillPower:22,skillNameKorean:'돌고래 고음',skillNameEnglish:'Dolphin High Note',skillCooldown:16,skillDescription:'킥 폭발 넉백',gameplayEffect:'kick burst knockback',bodyRadius:18,fallbackColor:'#ffd33f',spritePath:'/assets/characters/kyungmin/sprite.png',portraitPath:'/assets/characters/kyungmin/portrait.png',motif:'🎤'},
{id:'hyunjun',nameKo:'홍현준',nameEn:'Hyunjun',role:'Melee Skirmisher',maxHp:162,baseMoveSpeed:122,attackType:'melee',attackPower:8,attackRange:39,preferredCombatDistance:33,attackCooldown:0.82,skillPower:14,skillNameKorean:'철학적 질문',skillNameEnglish:'Philosophical Question',skillCooldown:14,skillDescription:'혼란 킥 + 순간 가속',gameplayEffect:'confuse kick + short haste',bodyRadius:17,fallbackColor:'#2f3d5c',spritePath:'/assets/characters/hyunjun/sprite.png',portraitPath:'/assets/characters/hyunjun/portrait.png',motif:'❓'},
{id:'chanyoung',nameKo:'박찬영',nameEn:'Chanyoung',role:'Melee Sustain',maxHp:186,baseMoveSpeed:122,attackType:'melee',attackPower:8,attackRange:41,preferredCombatDistance:35,attackCooldown:0.9,skillPower:20,skillNameKorean:'긍정 에너지',skillNameEnglish:'Positive Energy',skillCooldown:15,skillDescription:'회복 킥 + 방어',gameplayEffect:'heal + kick burst',bodyRadius:20,fallbackColor:'#f0a03a',spritePath:'/assets/characters/chanyoung/sprite.png',portraitPath:'/assets/characters/chanyoung/portrait.png',motif:'✨'},
{id:'hyowon',nameKo:'임효원',nameEn:'Hyowon',role:'Ranged Control',maxHp:158,baseMoveSpeed:122,attackType:'ranged',attackPower:7,attackRange:82,preferredCombatDistance:70,attackCooldown:1.02,skillPower:15,skillNameKorean:'수상한 장난',skillNameEnglish:'Sneaky Prank',skillCooldown:12,skillDescription:'함정 킥',gameplayEffect:'kick trap stun',bodyRadius:17,fallbackColor:'#ff8a3d',spritePath:'/assets/characters/hyowon/sprite.png',portraitPath:'/assets/characters/hyowon/portrait.png',motif:'🪤'},
{id:'dongha',nameKo:'최동하',nameEn:'Dongha',role:'Melee Utility',maxHp:172,baseMoveSpeed:122,attackType:'melee',attackPower:8,attackRange:43,preferredCombatDistance:36,attackCooldown:0.88,skillPower:14,skillNameKorean:'아이디어 폭주',skillNameEnglish:'Idea Overdrive',skillCooldown:12,skillDescription:'기믹 킥',gameplayEffect:'kick + utility slow',bodyRadius:19,fallbackColor:'#91a3ad',spritePath:'/assets/characters/dongha/sprite.png',portraitPath:'/assets/characters/dongha/portrait.png',motif:'⚙️'},
{id:'heesun',nameKo:'장희선',nameEn:'Heesun',role:'Ranged Precision',maxHp:154,baseMoveSpeed:122,attackType:'ranged',attackPower:7,attackRange:90,preferredCombatDistance:74,attackCooldown:1.04,skillPower:20,skillNameKorean:'예쁜 필기구 투척',skillNameEnglish:'Pretty Stationery Throw',skillCooldown:10,skillDescription:'정밀 킥 투척',gameplayEffect:'ranged poke + kick burst',bodyRadius:16,fallbackColor:'#ff77b7',spritePath:'/assets/characters/heesun/sprite.png',portraitPath:'/assets/characters/heesun/portrait.png',motif:'✏️'},
{id:'soeun',nameKo:'박소은',nameEn:'Soeun',role:'Ranged Harass',maxHp:160,baseMoveSpeed:122,attackType:'ranged',attackPower:7,attackRange:80,preferredCombatDistance:68,attackCooldown:0.98,skillPower:13,skillNameKorean:'곤충 출몰',skillNameEnglish:'Bug Swarm',skillCooldown:11,skillDescription:'벌레 킥 난전',gameplayEffect:'panic kick + chip',bodyRadius:16,fallbackColor:'#f3d73a',spritePath:'/assets/characters/soeun/sprite.png',portraitPath:'/assets/characters/soeun/portrait.png',motif:'🐞'}
];
export const byId=(id:CharacterId)=>CHARACTERS.find(c=>c.id===id)!;
