'use client';
import { useEffect, useRef, useState } from 'react';
import { byId, CHARACTERS } from '@/game/characters';
import { CharacterId, Fighter, GameState, InputState } from '@/game/types';
const W=2400,H=1600,viewW=960,viewH=600;
const obstacles=[{x:240,y:180,w:200,h:120,label:'교실',color:'#dbeeff',solid:true},{x:1820,y:200,w:220,h:140,label:'편의점',color:'#ffe7b8',solid:true},{x:180,y:1120,w:280,h:180,label:'옥수수밭',color:'#dff4c0',solid:true},{x:1780,y:1140,w:300,h:180,label:'학원 복도',color:'#e6ddff',solid:true},{x:960,y:660,w:420,h:260,label:'운동장 중앙',color:'#d2f7dc',solid:false}];
function mkState(playerId:CharacterId):GameState{const ids=CHARACTERS.map(c=>c.id);const order=[playerId,...ids.filter(i=>i!==playerId)];const fighters: Fighter[]=order.map((id,i)=>({id:`f${i}`,charId:id,x:300+(i%4)*500,y:280+Math.floor(i/4)*600,vx:0,vy:0,radius:22,hp:byId(id).maxHp,alive:true,isPlayer:i===0,lastAttack:-99,lastSkill:-99,facing:{x:1,y:0},status:{slowUntil:0,stunUntil:0,confuseUntil:0,defenseUntil:0,shieldUntil:0,panicUntil:0,speedUntil:0}}));
return {fighters,obstacles,safeZone:{x:W/2,y:H/2,radius:900,minRadius:170,shrinkPerSec:3.6,tick:0},projectiles:[],traps:[],devices:[],effects:[],time:0,elapsed:0,result:'playing'};}
export function GameCanvas({character,onResult}:{character:CharacterId;onResult:(r:'victory'|'defeat')=>void}){const cv=useRef<HTMLCanvasElement>(null);const [hud,setHud]=useState({hp:0,max:0,alive:8,skill:0,t:0,out:false,name:''});
useEffect(()=>{const input:InputState={up:false,down:false,left:false,right:false,attack:false,skill:false};const down=(e:KeyboardEvent)=>{if(['w','ArrowUp'].includes(e.key))input.up=true; if(['s','ArrowDown'].includes(e.key))input.down=true;if(['a','ArrowLeft'].includes(e.key))input.left=true;if(['d','ArrowRight'].includes(e.key))input.right=true;if(e.key===' ')input.attack=true;if(e.key==='e'||e.key==='E')input.skill=true;}; const up=(e:KeyboardEvent)=>{if(['w','ArrowUp'].includes(e.key))input.up=false; if(['s','ArrowDown'].includes(e.key))input.down=false;if(['a','ArrowLeft'].includes(e.key))input.left=false;if(['d','ArrowRight'].includes(e.key))input.right=false;if(e.key===' ')input.attack=false;if(e.key==='e'||e.key==='E')input.skill=false;};window.addEventListener('keydown',down);window.addEventListener('keyup',up);
const state=mkState(character); let raf=0,last=performance.now(); const loop=(now:number)=>{const dt=Math.min((now-last)/1000,0.033);last=now;state.time+=dt; state.elapsed+=dt; tick(state,input,dt); draw(state,cv.current!); const p=state.fighters[0], def=byId(p.charId); setHud({hp:Math.max(0,p.hp),max:def.maxHp,alive:state.fighters.filter(f=>f.alive).length,skill:Math.max(0,def.skillCooldown-(state.time-p.lastSkill)),t:state.elapsed,out:dist(p.x,p.y,state.safeZone.x,state.safeZone.y)>state.safeZone.radius,name:def.nameKo}); if(state.result!=='playing'){onResult(state.result); return;} raf=requestAnimationFrame(loop);}; raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);};},[character,onResult]);
return <div><canvas ref={cv} width={viewW} height={viewH}/><div className='hud'>{hud.name} HP {hud.hp.toFixed(0)}/{hud.max} | 생존 {hud.alive} | 스킬 {hud.skill.toFixed(1)}s | {hud.t.toFixed(0)}s {hud.out?'| ⚠ 안전지대 밖':''}<br/>이동: WASD/화살표 공격:Space 스킬:E</div></div>}
function dist(x:number,y:number,x2:number,y2:number){return Math.hypot(x-x2,y-y2)}
function tick(s:GameState,i:InputState,dt:number){const p=s.fighters[0]; s.safeZone.radius=Math.max(s.safeZone.minRadius,s.safeZone.radius-s.safeZone.shrinkPerSec*dt); s.safeZone.tick+=dt; if(s.safeZone.tick>1){s.safeZone.tick=0; s.fighters.filter(f=>f.alive && dist(f.x,f.y,s.safeZone.x,s.safeZone.y)>s.safeZone.radius).forEach(f=>f.hp-=6);} s.fighters.forEach((f,idx)=>{if(!f.alive)return; const c=byId(f.charId); let dx=0,dy=0; if(f.status.stunUntil>s.time){} else if(f.isPlayer){dx=(i.right?1:0)-(i.left?1:0);dy=(i.down?1:0)-(i.up?1:0);} else {const t=chooseTarget(s,idx); if(dist(f.x,f.y,s.safeZone.x,s.safeZone.y)>s.safeZone.radius+30){dx=s.safeZone.x-f.x;dy=s.safeZone.y-f.y;} else if(t){dx=t.x-f.x;dy=t.y-f.y; if(Math.random()<0.007)useSkill(s,f);} if(f.status.confuseUntil>s.time||f.status.panicUntil>s.time){dx+=(Math.random()-0.5)*200;dy+=(Math.random()-0.5)*200;} if(t && dist(f.x,f.y,t.x,t.y)<c.attackRange+8)attack(s,f);} if(i.attack&&f.isPlayer)attack(s,f); if(i.skill&&f.isPlayer)useSkill(s,f); const l=Math.hypot(dx,dy)||1; let sp=c.speed; if(f.status.slowUntil>s.time)sp*=0.6;if(f.status.speedUntil>s.time)sp*=1.35; f.vx=dx/l*sp;f.vy=dy/l*sp; f.x+=f.vx*dt;f.y+=f.vy*dt; f.x=Math.min(W-20,Math.max(20,f.x));f.y=Math.min(H-20,Math.max(20,f.y)); obstacles.forEach(o=>{if(o.solid && f.x>o.x-f.radius&&f.x<o.x+o.w+f.radius&&f.y>o.y-f.radius&&f.y<o.y+o.h+f.radius){if(f.x<o.x)f.x=o.x-f.radius; else if(f.x>o.x+o.w)f.x=o.x+o.w+f.radius; if(f.y<o.y)f.y=o.y-f.radius; else if(f.y>o.y+o.h)f.y=o.y+o.h+f.radius;}}); if(f.hp<=0){f.alive=false;}});
// effects
s.projectiles=s.projectiles.filter(pr=>{pr.x+=pr.vx*dt;pr.y+=pr.vy*dt;pr.ttl-=dt; const hit=s.fighters.find(f=>f.alive&&f.id!==pr.ownerId&&dist(f.x,f.y,pr.x,pr.y)<f.radius+pr.r); if(hit){hit.hp-=pr.dmg; return false;} return pr.ttl>0;}); s.traps=s.traps.filter(t=>{t.ttl-=dt; s.fighters.forEach(f=>{if(f.alive&&f.id!==t.ownerId&&dist(f.x,f.y,t.x,t.y)<f.radius+t.r){f.hp-=8;f.status.stunUntil=s.time+0.9;t.ttl=0;}}); return t.ttl>0;});
const alive=s.fighters.filter(f=>f.alive); if(!p.alive)s.result='defeat'; else if(alive.length===1 && alive[0].isPlayer)s.result='victory';}
function chooseTarget(s:GameState,i:number){const me=s.fighters[i]; return s.fighters.filter(f=>f.alive&&f.id!==me.id).sort((a,b)=>dist(me.x,me.y,a.x,a.y)-dist(me.x,me.y,b.x,b.y))[0];}
function attack(s:GameState,f:Fighter){const c=byId(f.charId); if(s.time-f.lastAttack<c.attackCooldown)return;f.lastAttack=s.time; s.effects.push({x:f.x,y:f.y,r:c.attackRange,ttl:0.15,kind:'attack',ownerId:f.id}); s.fighters.forEach(t=>{if(t.alive&&t.id!==f.id&&dist(f.x,f.y,t.x,t.y)<c.attackRange+t.radius){t.hp-=c.attackPower*(t.status.defenseUntil>s.time?0.7:1)*(f.status.shieldUntil>s.time?0.9:1);}})}
function useSkill(s:GameState,f:Fighter){const c=byId(f.charId); if(s.time-f.lastSkill<c.skillCooldown)return; f.lastSkill=s.time; const near=s.fighters.filter(t=>t.alive&&t.id!==f.id&&dist(f.x,f.y,t.x,t.y)<190);
if(c.id==='juwon'){near.forEach(t=>t.status.slowUntil=s.time+2.5);f.status.shieldUntil=s.time+2.5;s.effects.push({x:f.x,y:f.y,r:140,ttl:2.5,kind:'bell',ownerId:f.id});}
if(c.id==='kyungmin'){near.forEach(t=>{t.hp-=15;t.status.stunUntil=s.time+0.55;const dx=t.x-f.x,dy=t.y-f.y,l=Math.hypot(dx,dy)||1;t.x+=dx/l*65;t.y+=dy/l*65});s.effects.push({x:f.x,y:f.y,r:130,ttl:0.35,kind:'wave',ownerId:f.id});}
if(c.id==='hyunjun'){near.forEach(t=>t.status.confuseUntil=s.time+2.2);f.status.speedUntil=s.time+2.2;s.effects.push({x:f.x,y:f.y,r:120,ttl:2.2,kind:'q',ownerId:f.id});}
if(c.id==='chanyoung'){f.hp=Math.min(byId(f.charId).maxHp,f.hp+25);f.status.defenseUntil=s.time+3;s.effects.push({x:f.x,y:f.y,r:90,ttl:1.4,kind:'heal',ownerId:f.id});}
if(c.id==='hyowon')s.traps.push({x:f.x,y:f.y,r:20,ownerId:f.id,ttl:8});
if(c.id==='dongha'){const kinds:['spring','slow','snack','drone']=['spring','slow','snack','drone'];const k=kinds[Math.floor(Math.random()*4)]; if(k==='spring')near.forEach(t=>{const dx=t.x-f.x,dy=t.y-f.y,l=Math.hypot(dx,dy)||1;t.x+=dx/l*90;t.y+=dy/l*90}); if(k==='slow')near.forEach(t=>t.status.slowUntil=s.time+2.3); if(k==='snack')f.hp=Math.min(byId(f.charId).maxHp,f.hp+15); if(k==='drone'){const t=near[0];if(t)t.hp-=20;} s.effects.push({x:f.x,y:f.y,r:110,ttl:1,kind:k,ownerId:f.id});}
if(c.id==='heesun'){const t=chooseTarget(s,s.fighters.indexOf(f)); if(t){const dx=t.x-f.x,dy=t.y-f.y,l=Math.hypot(dx,dy)||1;s.projectiles.push({x:f.x,y:f.y,vx:dx/l*360,vy:dy/l*360,r:7,ownerId:f.id,ttl:1.8,dmg:24,color:'#7ed957'})}}
if(c.id==='soeun'){const t=near[0]; if(t){t.status.panicUntil=s.time+2.5; for(let k=0;k<5;k++)setTimeout(()=>{if(t.alive)t.hp-=4;},k*400);} s.effects.push({x:f.x,y:f.y,r:120,ttl:1.8,kind:'bug',ownerId:f.id});}
}
function draw(s:GameState,can:HTMLCanvasElement){const ctx=can.getContext('2d')!; const p=s.fighters[0]; const camX=Math.max(0,Math.min(W-viewW,p.x-viewW/2)), camY=Math.max(0,Math.min(H-viewH,p.y-viewH/2)); ctx.clearRect(0,0,viewW,viewH); ctx.fillStyle='#f4f1e8';ctx.fillRect(0,0,viewW,viewH); obstacles.forEach(o=>{ctx.fillStyle=o.color;ctx.fillRect(o.x-camX,o.y-camY,o.w,o.h);ctx.fillStyle='#555';ctx.fillText(o.label,o.x-camX+8,o.y-camY+18)});
ctx.fillStyle='rgba(220,75,105,.18)';ctx.fillRect(0,0,viewW,viewH);ctx.save();ctx.beginPath();ctx.arc(s.safeZone.x-camX,s.safeZone.y-camY,s.safeZone.radius,0,Math.PI*2);ctx.clip();ctx.clearRect(0,0,viewW,viewH);ctx.restore(); ctx.strokeStyle='#ff4b67';ctx.lineWidth=3;ctx.beginPath();ctx.arc(s.safeZone.x-camX,s.safeZone.y-camY,s.safeZone.radius,0,Math.PI*2);ctx.stroke();
s.effects=s.effects.filter(e=>{e.ttl-=1/60;ctx.strokeStyle='#222';ctx.beginPath();ctx.arc(e.x-camX,e.y-camY,e.r,0,Math.PI*2);ctx.stroke(); return e.ttl>0;}); s.traps.forEach(t=>{ctx.fillStyle='#8a5';ctx.beginPath();ctx.arc(t.x-camX,t.y-camY,t.r,0,Math.PI*2);ctx.fill();}); s.projectiles.forEach(pr=>{ctx.fillStyle=pr.color;ctx.beginPath();ctx.arc(pr.x-camX,pr.y-camY,pr.r,0,Math.PI*2);ctx.fill();});
for(const f of s.fighters){if(!f.alive)continue; const c=byId(f.charId); ctx.fillStyle=c.fallbackColor;ctx.beginPath();ctx.ellipse(f.x-camX,f.y-camY,f.radius*(f.charId==='hyunjun'?0.8:1.1),f.radius*(f.charId==='juwon'?1.2:1),0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillText(c.motif,f.x-camX-8,f.y-camY+4); ctx.fillStyle='#111';ctx.fillText(c.nameKo,f.x-camX-20,f.y-camY-f.radius-8); ctx.fillStyle='#e55';ctx.fillRect(f.x-camX-24,f.y-camY+f.radius+6,48,5);ctx.fillStyle='#5f5';ctx.fillRect(f.x-camX-24,f.y-camY+f.radius+6,48*(f.hp/byId(f.charId).maxHp),5);} }
